travis:
  secure:
    BINSTAR_TOKEN: 6B4KF/U1aRP+hQ8TtStY5myVcT9a84uOFFEaHZFPqbfnfs0K6Q4+sbn9PmxO4/70mRU8qtXwmzOYQ+badPzsRywD7ReyNifyAwTqg1HyIibFJMcEMBi6Cslc57Rufh4RvtGPCOuFVh7NAnRKAPgcdAI2M0k6izUPq3Kt0i7gTUZY54BZ2Wtw0601NDsA78U/eWNl0Afm0KwXio4Vyz5qWA0MwQkc8ZkFYnZb+STt6lBM51TIkMNvac79IqyxHuWO+HWJPazTETUnach3r5Z1x73AI81swKVaUh1go1BuwzIngl8nNxF+PlrLQhxwcHfQ7ZjPfyJIdHQDnyN/2gNeeWBapk/LZg/2j6vRQ8mBs/6XGB62BdWSwTefryi1u6zLIw2u152J90JDng/ZZedd/IEjDR+Q6Qh928Dbm+5YurWU1+SBjW7wHVf6HX+mlg5kGeuttCU3dWf58CZ1iWfz1GDmtlYy8BYTVGfOC7iGTQUf/Gm3G6Hq5SECRbJ+2pKZwxp6vpsxxKwXPAddQbFXOrSUgELgix+G+OhVnz/ufHF2B9T1g/dAlvy/AKtU6FIGdgsur8PGT6rV7akqJboMTrggXGSjzxB36PF5tT/j3BPctQ2VXnj464qXUs739FlD9rvna322GUmzYkL8ls5UumPhSBnxMJSgJWCUR5JIx+0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
