travis:
  secure:
    BINSTAR_TOKEN: QPOkzgENUdzXlCnW4xpegwYcZD6r3VSA8pxCjPkDNB2YhAmcwMD37cii9TWXnrKYXDCdObXGc8hQ4h3vsOBXxje0CwUcYvFIByt5fCi/MdzHNTqd9uux5PWchuyisopNkzE0njANc6zw4+QmXNh0WAxx/qtsu61p5VbFQUWeR8nUb/Y+kaBFR5Eu1wpM5uUv0MyQETGdlmxTIr8S+A7aN7H5b1FGGaPawrlyIJgMuC9ZrEk7tTVrc84CmvtBQc/dlJLRRQ8f/EFu45X34iBPLsdI+bHRowAdMrVWXcMcYsJJ+2a8W8oBdM8loxTA2pxTq7M5zjg6I2DLmNfI6fhKqkNjBc3ZNINtGDwp1l0XOkeUFKWV56jsr0+CDR3nbJ8BQR+M1ErXKp7A7oEANx6HfrtGB0PjHqc8/h7oEFtxcMDJ6j1HEAOWKdYVRsxGbcYbRbJ8CbZXqLRZYI25i2EKk3PYwf+ow5CEEXjoL13/YL5TvJOpTPTmiowYQWkrps6GsM2HOweCmAKTBI5rJFbLtl+M9wxd8y2dPk0FYoK9TcN/lvsXICnFZ0k7rE/ZBr3YUtYWd5FXmIVYNHEsHMBZUG/pII6KPnpomj6OuQJybnr11y4Mj0bFsUkdIQXaAJA+2D129vsD7hflQQ/u6fALVyegR9YuEXHQQ22GRj9fdgI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
